### PR TITLE
Pomodoro timer

### PR DESCRIPTION
**Pull request by adedayoprcs**
I created pomodoro timer

### CODE REVIEW

**Comment by adedayoprcs** [comment]
I created pomodoro timer

**Review by iamwatchdogs — APPROVED** [review]
Reviewed and Approved by @iamwatchdogs.

**Comment by iamwatchdogs** [comment]
Thank you for contributing @adedayoprcs, make sure to check your contributions on [GitHub Pages](https://grow-with-open-source.github.io/Python-Projects/).

**Comment by adedayoprcs** [comment]
Thanks!

**Pull request merged**
